<?php require_once __DIR__ . '/../includes/session_bootstrap.php'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Disclaimer — Arigato Store</title>
  <meta name="description" content="Disclaimer for Arigato Store: AI-generated results vary, sample images are examples not guarantees, and payments are processed by SuperProfile."/>
  <meta name="robots" content="index, follow"/>
  <link rel="canonical" href="https://arigatodevan.com/digital_store/disclaimer.php"/>
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="Disclaimer — Arigato Store"/>
  <meta property="og:description" content="What our AI couple prompts can and cannot promise, how SuperProfile handles payments, and your responsibilities as a buyer."/>
  <meta property="og:url" content="https://arigatodevan.com/digital_store/disclaimer.php"/>
  <meta name="twitter:card" content="summary_large_image"/>
  <link rel="icon" href="/favicon.ico" type="image/x-icon"/>
  <link rel="stylesheet" href="css/store.css"/>
  <style>
    .policy-page { max-width: 720px; margin: 0 auto; padding: 60px 20px 80px; }
    .policy-label {
      display: inline-block; background: #f8f4ef; color: #8b6914;
      border: 1px solid #e5d5b0; border-radius: 100px;
      font-size: 0.72rem; font-weight: 700; letter-spacing: 0.1em;
      text-transform: uppercase; padding: 5px 14px; margin-bottom: 16px;
    }
    .policy-title {
      font-family: 'Playfair Display', serif;
      font-size: clamp(2rem, 5vw, 2.8rem); font-weight: 900;
      color: var(--text-primary); margin-bottom: 8px; line-height: 1.15;
    }
    .policy-intro {
      font-size: 0.92rem; color: var(--text-secondary);
      line-height: 1.8; margin-bottom: 10px;
    }
    .policy-updated { font-size: 0.78rem; color: var(--text-muted); margin-bottom: 40px; }
    .policy-section { margin-bottom: 36px; padding-bottom: 36px; border-bottom: 1px solid var(--border); }
    .policy-section:last-child { border-bottom: none; }
    .policy-section h2 {
      font-family: 'Playfair Display', serif; font-size: 1.15rem; font-weight: 800;
      color: var(--text-primary); margin-bottom: 12px;
      display: flex; align-items: center; gap: 10px;
    }
    .policy-section h2 .sec-icon {
      width: 32px; height: 32px; border-radius: 8px; background: #f8f4ef;
      display: inline-flex; align-items: center; justify-content: center;
      font-size: 0.9rem; flex-shrink: 0; color: #8b6914;
    }
    .policy-section p, .policy-section li {
      font-size: 0.88rem; color: var(--text-secondary);
      line-height: 1.8; margin-bottom: 10px;
    }
    .policy-section ul { padding-left: 20px; }
    .policy-section ul li::marker { color: var(--accent-warm); }
    .policy-section a { color: var(--text-primary); font-weight: 600; }
    .highlight-box {
      background: #f8f4ef; border-left: 3px solid #c9a96e;
      border-radius: 8px; padding: 14px 18px; margin: 14px 0;
      font-size: 0.85rem; color: var(--text-secondary); line-height: 1.7;
    }
  </style>
</head>
<body>
<?php include 'store_nav.php'; ?>

<main class="policy-page">
  <span class="policy-label">Legal</span>
  <h1 class="policy-title">Disclaimer</h1>
  <p class="policy-intro">Arigato Store sells AI prompts — written instructions you run inside your own AI tool. This page explains, in plain language, what those prompts can realistically do, what we cannot promise, and who handles your money.</p>
  <p class="policy-updated">Last updated: July 2026</p>

  <div class="policy-section">
    <h2><span class="sec-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg></span> What You Are Buying</h2>
    <p>Every product in this store is a <strong>digital prompt</strong> — text you copy into an AI image tool, usually along with your own photo. You are buying the instructions and the guidance that comes with them. You are not buying the sample images, an editing service, or any AI subscription.</p>
    <p>Because a prompt is delivered in full the moment you pay, purchases are treated as final. The complete position on delivery and refunds is in our <a href="terms.php">Terms &amp; Conditions</a>.</p>
  </div>

  <div class="policy-section">
    <h2><span class="sec-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg></span> Sample Images Are Examples, Not Guarantees</h2>
    <p>The images shown on each product page were generated by us using that exact prompt, so they are an honest representation of the style you can expect. They are not a promise of an identical result.</p>
    <div class="highlight-box">
      AI image tools are <strong>non-deterministic</strong>. The same prompt, run twice, produces two different images. Your output will also differ from ours because your photo, faces, outfits, lighting and the tool's current model version are all different.
    </div>
    <p>Our prompts are engineered to keep facial features as close to your uploaded photo as possible, and that is the whole point of them — but the degree of resemblance depends heavily on the photo you provide. Clear, well-lit, front-facing photos give the best results; blurred, filtered, cropped or side-profile photos give weaker ones. Re-running a prompt with a better photo is normal practice, not a defect.</p>
  </div>

  <div class="policy-section">
    <h2><span class="sec-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="1" y="4" width="22" height="16" rx="2" ry="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg></span> Payments Are Handled by SuperProfile</h2>
    <p>All store purchases are processed by <strong>SuperProfile</strong>, an independent third-party payment platform. Prices are in Indian Rupees (₹).</p>
    <ul>
      <li>When you click "Unlock", you leave Arigato Store and complete payment on SuperProfile's own secure checkout.</li>
      <li>Your card, UPI and banking details are entered on SuperProfile and its payment gateways. <strong>Arigato Store never receives or stores them.</strong></li>
      <li>Your payment receipt is issued and emailed by SuperProfile. Their charge may appear on your statement under their name rather than ours.</li>
      <li>While you are on their checkout, SuperProfile's own terms and privacy policy apply to that transaction.</li>
      <li>We are not responsible for bank declines, UPI timeouts, gateway downtime, or other failures that happen on the payment side. If money left your account but access did not arrive, <a href="contact.php">raise a ticket</a> with your receipt and we will sort it out.</li>
    </ul>
  </div>

  <div class="policy-section">
    <h2><span class="sec-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg></span> Third-Party AI Tools</h2>
    <p>Our prompts are written and tested for <strong>Google Gemini (Nano Banana)</strong> and <strong>ChatGPT Image</strong>. Arigato Store is an independent store and is <strong>not affiliated with, endorsed by, or partnered with</strong> Google, OpenAI, SuperProfile, Instagram, or any other company named on this site. Those names are used only to describe which tools a prompt is meant for, and all trademarks belong to their respective owners.</p>
    <ul>
      <li>You need your own account on the AI tool you choose. Free tiers usually work, but come with daily limits set by that provider.</li>
      <li>These providers update their models, safety filters and pricing without notice. An update can change how a prompt behaves. When we spot that, we revise the prompt and the updated version appears in <a href="my_purchases.php">My Purchases</a> at no extra cost.</li>
      <li>You must follow the terms and content policies of whichever AI tool you use, including their rules on how generated images may be used.</li>
      <li>A prompt being refused or filtered by an AI provider's safety system is outside our control.</li>
    </ul>
  </div>

  <div class="policy-section">
    <h2><span class="sec-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg></span> No Guarantee of Reach, Growth or Income</h2>
    <p>Nothing in this store is a promise of results beyond the prompt itself. We do not guarantee views, likes, followers, virality, client work, or any earnings from images you create. Social platforms decide what they show, and that is entirely their call. Any performance figures mentioned anywhere on this site describe past examples, not what you should expect.</p>
    <p>Our content is provided for creative and informational purposes only and is not legal, financial, or professional advice.</p>
  </div>

  <div class="policy-section">
    <h2><span class="sec-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></span> Your Responsibility as the Creator</h2>
    <p>You control what you generate, so the responsibility for it sits with you. When you use our prompts:</p>
    <ul>
      <li>Only upload photos you own or have permission to use. For couple prompts, that means your partner has agreed too.</li>
      <li>Do not create images of another real person, a public figure, or a minor without proper consent.</li>
      <li>Do not use our prompts to produce misleading, defamatory, explicit, hateful, or unlawful content.</li>
      <li>Where a platform or context requires it, be transparent that an image is AI-generated.</li>
    </ul>
    <p>Uploading your photo to an AI tool means sharing it with that provider under <em>their</em> privacy policy. Arigato Store never receives the photos you use. How we handle the limited data we do collect is set out in our <a href="privacy.php">Privacy Policy</a>.</p>
  </div>

  <div class="policy-section">
    <h2><span class="sec-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg></span> Limitation of Liability</h2>
    <p>Prompts and guides are provided <strong>"as is"</strong>, without warranty of any kind. To the fullest extent permitted by law, Arigato Store is not liable for indirect or consequential losses arising from your use of our prompts or of any third-party AI tool. Where liability cannot be excluded, it is limited to the amount you paid for the specific product concerned.</p>
    <p>This disclaimer does not affect rights you have under applicable Indian consumer protection law.</p>
  </div>

  <div class="policy-section">
    <h2><span class="sec-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg></span> Questions</h2>
    <p>If anything here is unclear, ask before you buy — we would rather answer a question than deal with a disappointed customer. <a href="contact.php">Raise a support ticket</a> or email <strong>devansh.grow@gmail.com</strong>. Common questions are already answered on our <a href="faq.php">FAQ page</a>.</p>
  </div>
</main>

<?php include 'store_footer_links.php'; ?>
<?php include '../footer.php'; ?>
<script src="js/store.js"></script>
<?php include 'store_firebase_js.php'; ?>
</body>
</html>
